server:
  port: 8088

spring:
  application:
    name: ead-config-service
  cloud:
    config:
      server:
        git:
          uri:
            username:
              password:


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

