ead:
  serviceRegistry:
    username: admin
    password: 'admin' 
  auth:
    jwtSecret: 0xbqF4Vgec0ih8DG7Xqpq15weLrQSB+lU7aF6ml7u9yW0krxfXNiN3P3QyQZ9vyfr33bhrV04V4ljw/VpPqqexWm4+31cPfxuyaDlSTeRI8=
    jwtExpirationMs: 1440000     
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost