server:
  port: 8086

spring:
  application:
    name: ead-payment-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-payment-v2
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        jdbc:
          lob.non-contextual-creation: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://beugxnyy:Fc9DwOEnSkBg4ymBmQ76lxBJCprVaubq@beaver.rmq.cloudamqp.com/beugxnyy

ead:
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue: ead.userevent.ms.payment    

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO  

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

