server:
  port: 8083
  servlet:
    context-path: '/ead-course-service/'

spring:
    application:
      name: ead-course-service
    datasource:
      url: jdbc:postgresql://localhost:5432/ead-course-v2
      username: postgres
      password: admin
    jpa:
      hibernate:
        ddl-auto: update
      show_sql: true
      properties:
        hibernate:
          jdbc:
            lob.non-contextual-creation: true
    output:
      ansi:
        enabled: always
    rabbitmq:
      addresses: amqps://beugxnyy:Fc9DwOEnSkBg4ymBmQ76lxBJCprVaubq@beaver.rmq.cloudamqp.com/beugxnyy

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-auth-service/ead-auth-service'
  broker:
    exchange:
      userEventExchange: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification    
management:
  endpoints:
    web:
      exposures:
        include:
          - refresh
          - health           
